footer
Dron010/filmoteka pull request #16
Opened 2021-11-07 07:46 UTC by T-jorven

2021-11-07 11:55 UTC, Dron010 commented on src/sass/layout/_footer.scss
> +}
1.Разобраться с настройками Prettier, скобки отступы должны быть отредактированы одинаково (для примера посмотри .container)
2. Имена классов должны быть по методологии BEM (https://goit.global/textbooks/html-css-a7u5xv/v1/docs/lesson-14/intro/#)

2021-11-07 11:55 UTC, Dron010 commented on src/partial/layouts/footer.html
> +</footer>
1.Разобраться с настройками Prettier, скобки отступы должны быть отредактированы одинаково (для примера посмотри .container)

2021-11-07 11:55 UTC, Dron010 commented on src/partial/layouts/footer.html
> +</svg>
```
<svg class="icon-heart-svg">
        <use href="./././images/icon/sprite.svg#icon-heart"></use>
</svg>
```
вот так должно быть.... каждый вложенный элемент должен быть сдвинут относительно родительского

2021-11-07 11:55 UTC, Dron010 commented on src/images/icon/sprite.svg
> +</symbol>
поровнять вложенности элементов

2021-11-07 11:55 UTC, Dron010 commented on src/sass/main.scss
> +@import './layout/footer';
import должен быть в //footer а не в //header

2021-11-07 14:26 UTC, vladislav-slobodenjuk commented on src/sass/layout/_footer.scss
> +    margin-top: 10px
Разве иконке здесь нужен верхний марджин?

2021-11-07 14:33 UTC, vladislav-slobodenjuk commented on src/sass/layout/_footer.scss
> +    margin-top: 10px
Можно сделать две <p> с display: inline-block и первой <p> задать margin-bottom. Потом в медиа правиле от 768 обнулить отступ.
А то как есть получается, что margin-top бьет в пустоту для планшета и десктопа, так не должно быть

2021-11-07 20:10 UTC, Dron010 reviewed
доделать

2021-11-07 20:10 UTC, Dron010 commented on src/partial/layouts/footer.html
> +</footer>
Проверить валидатором на ошибки и пофиксить http://validator.w3.org/nu/#textarea

2021-11-07 20:10 UTC, Dron010 commented on src/sass/layout/_footer.scss
> +  &-container {
&-НЕ так, вот так &__ должно быть (footer__container  и следовательно -> &__container )

2021-11-07 20:11 UTC, Dron010 commented on src/sass/layout/_footer.scss
> +  &-container {
поменять соответственно все что есть а не только container

2021-11-07 22:52 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_footer.scss
> +    @media screen and (min-width: $mobile) {
gdfgdf

2021-11-07 23:00 UTC, Viktor-Kostiuchenko requested changes

2021-11-07 23:00 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/footer.html
> +</footer>
Проверить валидатором на ошибки и пофиксить http://validator.w3.org/nu/#textarea

2021-11-07 23:00 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_footer.scss
> +  &-container {
&-НЕ так, вот так &__ должно быть (footer__container и следовательно -> &__container )

поменять соответственно все что есть а не только container

2021-11-07 23:00 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/footer.html
> +    <div class="container footer-container">
класс поменять с footer-container на footer__container

2021-11-07 23:00 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/footer.html
> +    <p class="footer-text">&#169  2020 | All Rights Reserved | Developed with
класс поменять на footer__text

2021-11-07 23:00 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/footer.html
> +       <svg class="icon-heart-svg">
класс поменять на footer__icon-heart

2021-11-07 23:00 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/footer.html
> +       <span class="footer-text__authors">GoIT Students</span>
класс поменять на footer__text-authors

2021-11-07 23:00 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_footer.scss
> +.icon-heart-svg {
поменять класс согласно тому, что будет написан в html выше

2021-11-08 00:09 UTC, Viktor-Kostiuchenko requested changes

2021-11-08 00:09 UTC, Viktor-Kostiuchenko commented on src/images/icon/sprite.svg
>      <symbol id="sun" viewBox="0 0 32 32">
ниже расписаны комменты по правкам

2021-11-08 08:38 UTC, Dron010 requested changes
поправить

2021-11-08 08:38 UTC, Dron010 commented on src/sass/layout/_footer.scss
> +}
перенести в .footer{ 
&__icon-heart{}
 }

2021-11-08 08:38 UTC, Dron010 commented on src/sass/layout/_footer.scss
> +  }
&__icon-heart{} вставить перед  &__text-authors{}

2021-11-08 08:57 UTC, Dron010 requested changes

2021-11-08 08:57 UTC, Dron010 commented on src/sass/layout/_footer.scss
> +}
&__icon-heart и  &__text-authors поменять местами, они должны идти в таком же порядке как идут в дереве html

2021-11-08 09:38 UTC, Dron010 approved these changes

2021-11-08 09:39 UTC, merged