Origin/btn-base
Dron010/filmoteka pull request #17
Opened 2021-11-07 13:05 UTC by LarysaTymoshenko

2021-11-07 13:55 UTC, vladislav-slobodenjuk commented on src/partial/templates/btnBase.hbs
> +    <li class="btn-base-item">
btn-base__item

2021-11-07 14:15 UTC, Dron010 commented on src/sass/base/_btn.scss
> +}
1.создай ветку новую btn-base-style 
2. скопируй в нее один файл src/sass/base/_btn.scss 
3. в нем оставляешь:
  border-radius: 5px;
  font-size: 12px;
  width: 130px;
  height: 44px;
 border: none;
  @media screen and(min-width:$tablet) {
    width: 136px;
  }
4. Отправляешь на мерж

2021-11-07 20:54 UTC, Dron010 reviewed
отсутствуют файлы   @extend %button и другие, провести локальный мерж с мейна.

2021-11-07 20:54 UTC, Dron010 commented on src/index.html
> +   </header>
это тут не нужно, убрать...

2021-11-07 20:54 UTC, Dron010 commented on src/sass/base/_container.scss
> -}
Почему оно удаленно? Вернуть назад...

2021-11-07 20:54 UTC, Dron010 commented on src/sass/base/_global-stile.scss
> -}
Почему оно удаленно? Вернуть назад...

2021-11-07 20:54 UTC, Dron010 commented on src/sass/base/_reset.scss
> -}
Почему оно удаленно? Вернуть назад...

2021-11-07 20:54 UTC, Dron010 commented on src/partial/templates/btnBase.hbs
> +</ul>
Этот код будет вставлен в секцию хедера, переименовать классы и отдать Даше для вставки в хедер, тут удалить.
header{
&__list-btn{}
&__item-btn{}
&__btn{}
}

2021-11-07 20:54 UTC, Dron010 commented on src/sass/layout/_header-modal-btn.scss
> +}
классы привести к тому что указал на html

2021-11-07 20:54 UTC, Dron010 commented on src/sass/main.scss
> +@import './layout/header-modal-btn';
header-btn  - это не модульные кнопки это встроенный элемент в header

2021-11-08 06:15 UTC, Dron010 requested changes
доработать

2021-11-08 09:13 UTC, closed without merging