add fetch on API for all movies
Dron010/filmoteka pull request #19
Opened 2021-11-07 17:22 UTC by Falconoff

Написал ф-цию для запроса на API всех фильмов с заданием страницы (для пагинации пригодится)

2021-11-07 21:27 UTC, A-V-Kuzmich commented on src/index.js
> -import './js/api/api-service.js';
вернуть подключение назад

2021-11-07 21:27 UTC, A-V-Kuzmich commented on src/index.js
> +}
создать файл test-api в папке src\js\test и закинуть это все туда.

2021-11-07 21:27 UTC, Dron010 commented on src/js/api/api-service.js
> +};
**1.** привести к тому о чем говорили на собрании, к универсальному запросу. Аxios по дефолту подставляет baseURL и  API_KEY, приходить должны  из вне параметры для запросов:
по ключевому слову, 
id; 
movie week; 
по жанру.
**2.** Создать файл  в папке тест с названием test-api.js в котором сделать import src/js/api/api-service.js дальше сделать  4 запроса для проверки каждого варианта на работоспособность. Пример:
fetchAllMovies(по ключевому слову);
fetchAllMovies(id);
fetchAllMovies(movie week);
fetchAllMovies(по жанру);
после проверки закомментировать в файле test-api.js все строки.
**3.** добавить проверку на ошибку в .then (вызов функции "error();" и передача номера ошибки в нее )
**4.** комментарий отредактировать соответственно.

2021-11-08 00:12 UTC, Falconoff commented on src/js/api/api-service.js
> +};
Кроме поиска по жанру

2021-11-08 11:39 UTC, Dron010 requested changes

2021-11-08 11:39 UTC, A-V-Kuzmich commented on src/js/test/test-api.js
> +      console.log(`//============= RESULT of fetch ALL on ${page}-th page: =============//`);
console.log(`//============= RESULT of fetch ALL on ${page}-th page: =============//`); -убрать

2021-11-08 11:39 UTC, A-V-Kuzmich commented on src/js/test/test-api.js
> +      // console.log(result.results[7].original_title);
// console.log(result.results[7].original_title); - убрать

2021-11-08 11:39 UTC, A-V-Kuzmich commented on src/js/test/test-api.js
> +      console.log(`//============= RESULT of fetch 1 movie by ID: "${movie_id}" =============//`);
console.log(`//============= RESULT of fetch 1 movie by ID: "${movie_id}" =============//`); - убрать

2021-11-08 11:39 UTC, Dron010 commented on src/js/api/api-service.js
> +  return axios.get(`${query}&api_key=${API_KEY}`).then(response => response.data);
добавить .catch(onFetchError) сюда

2021-11-08 11:39 UTC, Dron010 commented on src/js/test/test-api.js
> +    .catch(onFetchError);
.catch(onFetchError); - убрать

2021-11-08 11:39 UTC, Dron010 commented on src/js/test/test-api.js
> +        `//============= RESULT of fetch movies by keyword (title) "${keyword}": =============//`,
`//============= RESULT of fetch movies by keyword (title) "${keyword}": =============//`, - убрать

2021-11-08 11:39 UTC, Dron010 commented on src/js/test/test-api.js
> +    .catch(onFetchError);
.catch(onFetchError); - убрать

2021-11-08 11:39 UTC, Dron010 commented on src/js/test/test-api.js
> +    .catch(onFetchError);
.catch(onFetchError); - убрать

2021-11-08 11:39 UTC, Dron010 commented on src/js/test/test-api.js
> +onFetchByKeyword('кин-дза-дза', 1);
onFetchByKeyword('кин-дза-дза', 1);  =>  //onFetchByKeyword('кин-дза-дза', 1);

2021-11-08 22:16 UTC, Dron010 requested changes
функции для теста можешь повыдёргивать с мейна (src\js\layout), там я их немного поменял и слил с общей веткой для работы, в тесте они должны быть закомментированы что бы не мешать основному функционалу, а служить чисто проверкой работоспособности запроса при нужде.   
В общем по правкам изменить название запроса и перетянуть функции в тест из файлов

2021-11-08 22:16 UTC, Dron010 commented on src/js/api/api-service.js
> +export const fetch = query => {
const fetch -> поменять название функции на   getApiData

2021-11-08 22:16 UTC, Dron010 commented on src/js/test/test-api.js
> +import { onFetchError } from '../components/notifications.js';
import { fetch } поменять на  import { getApiData}

2021-11-08 22:16 UTC, Dron010 commented on src/js/test/test-api.js
> +  let query = `/movie/${movie_id}?language=en-US`;
language=en-US - является не обязательным параметром в функции. Его нужно почистить во всех функциях

2021-11-09 01:10 UTC, Falconoff commented
Вроде исправил

2021-11-09 06:41 UTC, Dron010 approved these changes

2021-11-09 06:42 UTC, merged