Markup card list
Dron010/filmoteka pull request #20
Opened 2021-11-07 17:29 UTC by Bohdan-Ta

2021-11-07 21:15 UTC, Viktor-Kostiuchenko requested changes

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/header.html
> +<H1 class="visually-hidden">list movies</H1>
тег написан с большой буквы, а не маленькой

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +{{#each this}}
переименуй файл в film-cards или film-list (так как это должен быть список)

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/header.html
> +    <li class="film-list-item">
вот эти вся разметка после ul - убираем. Мы же ее подтягиваем через hbs

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/header.html
> +<div class="container main-conteiner">
опечатка в main-conteiner -> container

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +    <img class="film-picture" data-index="{{@index}}" src="https://image.tmdb.org/t/p/w500{{poster_path}}"
а что такое "@index"?  что он дает?

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/header.html
> +    <ul class="film-list">
дай лучше класс просто films. Так лучше будет по BEM работать

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +<li class="film-list-item">
класс films__item

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +  <div class="film-card">
класс films__card

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +    <img class="film-picture" data-index="{{@index}}" src="https://image.tmdb.org/t/p/w500{{poster_path}}"
класс films__picture

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +      alt="film card" />
а в alt можно тоже что-то из json подставить?

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +    <img class="film-picture" data-index="{{@index}}"
класс films__picture

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +      src="https://upload.wikimedia.org/wikipedia/commons/archive/c/c2/20170210132813%21No_image_poster.png" alt="content photo">
тоже в alt добавить описание из json

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +  <div class="film-info">
класс films__info

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +    <h2 class="film-name">{{title}}</h2>
класс films__name

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +    <div class="film-info-wrap">
класс films__info-wrapper

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +      <ul class="film-genre">
класс films__genre

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +        <li class="film-genre-item" data-index="{{this}}">{{this}}</li>
класс films__genre-item

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +        <li class="film-genre-item" data-index="{{this}}">{{this}}</li>
что здесь дает data-index?

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +      <span class="film-info-mark">|</span>
класс films__info-mark

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +      <p class="film-year">{{release_date}}</p>
класс films__info-year

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +      <span class="raiting">{{vote_average}}</span>
класс films__info-rating

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +.main-conteiner {
а тебе прям нужен отдельный класс для контейнера? 
общего класса container не достаточно? 

ну и не забудь название css-правил переписать на те, что в разметке

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +    transition: box-shadow 450ms cubic-bezier(0.4, 0, 0.2, 1);
для 450ms и cubic-bezier данные закинь в переменную

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +      box-shadow: 8px -6px 16px -2px rgba(73, 73, 73, 0.95);
цвета и тени - в переменную

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-card.hbs
> +      <span class="film-info-mark">|</span>
вот для info-mark, year rating возможно тоже стоит сделать через ul.
Чтобы потом стили для всех лишок одним правилом прописать

2021-11-07 21:15 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +  .film-genre,
выше писал, чтобы через ul сделать, чтобы для всех них был один стиль прописан

2021-11-07 21:25 UTC, Bohdan-Ta commented on src/partial/layouts/header.html
> +<H1 class="visually-hidden">list movies</H1>
Исправлено

2021-11-07 21:26 UTC, Bohdan-Ta commented on src/partial/layouts/header.html
> +<div class="container main-conteiner">
Исправлено

2021-11-07 21:28 UTC, vladislav-slobodenjuk commented on src/partial/templates/film-card.hbs
> +{{#each this}}
Сверстать карточку фильма это моя задача

2021-11-07 21:33 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +.main-conteiner {
Почему отдельный клас? - из за того что тот клас что есть учитывает только лево и право и то не так как при разных брейк поинтах. Верх и низ вообще не регулирует. Вот поэтому и решил сделать клас отдельный

2021-11-07 21:35 UTC, Bohdan-Ta commented on src/partial/layouts/header.html
> +    <ul class="film-list">
Переименовано

2021-11-07 21:35 UTC, Bohdan-Ta commented on src/partial/layouts/header.html
> +    <li class="film-list-item">
Убрал, это для того что бы была возможность посмотреть визуально

2021-11-07 22:03 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +    transition: box-shadow 450ms cubic-bezier(0.4, 0, 0.2, 1);
Кубик в переменных, он один для всех. А вот время, может оставим без переменной, так как оно может быть разное и без повторений. Или использовать одно для всего?

2021-11-07 22:08 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +      box-shadow: 8px -6px 16px -2px rgba(73, 73, 73, 0.95);
В переменные все перенес

2021-11-07 22:13 UTC, Bohdan-Ta commented on src/partial/templates/film-card.hbs
> +{{#each this}}
Влад, я не против, что бы ты это делал, но тогда я не совсем понимаю тогда, что мне нужно было сделать?

2021-11-07 22:38 UTC, Bohdan-Ta commented on src/partial/templates/film-card.hbs
> +    <img class="film-picture" data-index="{{@index}}" src="https://image.tmdb.org/t/p/w500{{poster_path}}"
https://handlebarsjs.com/api-reference/data-variables.html#index
Я использовал его как возможно один из идентификаторов для картинки. Там или картинка которая подтянута или дефолтная картинка, которую я вставил. Ее можно заменить, если не нравится

2021-11-07 22:42 UTC, vladislav-slobodenjuk commented on src/sass/main.scss
>  //footer
Здесь ошибка в имение импорта
Должно быть:
@import './layout/list-cards-movies';

2021-11-07 22:48 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +  .film-genre,
Витя, а почему через ul? Это же список в котором лежит li обязательно. Как по мне то <span> и <p> подходять симантичести для этого. А стили и так одни прописаны.

2021-11-07 22:49 UTC, vladislav-slobodenjuk commented on src/partial/templates/film-card.hbs
> +    <img class="film-picture" data-index="{{@index}}" src="https://image.tmdb.org/t/p/w500{{poster_path}}"
![image](https://user-images.githubusercontent.com/16687004/140664709-510f7e84-0b76-4ae5-8118-b9ae5dbd45bc.png)
из json от сервера это должен быть просто id

2021-11-07 22:55 UTC, Bohdan-Ta commented on src/sass/main.scss
>  //footer
Исправил

2021-11-07 23:00 UTC, Bohdan-Ta commented on src/partial/templates/film-card.hbs
> +    <img class="film-picture" data-index="{{@index}}" src="https://image.tmdb.org/t/p/w500{{poster_path}}"
понял, не настаиваю. Удалять сразу?

2021-11-08 10:54 UTC, Viktor-Kostiuchenko requested changes

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/header.html
> +<div class="container main-container">
класс на container--main-geometry, ну или что-то типа такое. Поскольку это модификатор

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-cards.hbs
> +      alt="film card" />
поменять alt на то, что приходит с API

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-cards.hbs
> +      src="https://upload.wikimedia.org/wikipedia/commons/archive/c/c2/20170210132813%21No_image_poster.png" alt="content photo">
поменять alt на то, что приходит с API

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-cards.hbs
> +      <span class="raiting">{{vote_average}}</span>
скорее это все же не "span " а "p"

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-cards.hbs
> +      <span class="films__info-mark">|</span>
я бы может эту | реализовал как псевдоэлемент after для films__year

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +    display: block;
у div по умолчанию уже стоит display: block

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +    margin-left: 5px;
здесь тоже padding а не margin

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +    font-weight: 500;
font-weight: 500;
  font-size: 12px;
  line-height: 1.33;
color: $primary-text-color;
  
  наследуются от body. Не нужно повторно указывать

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +  .films__info-mark,
поскольку мы .films__info-mark сделаем как псевдоэлемент - то стили нужно будет поправить

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +  .films__year {
font-weight: 500;
    font-size: 12px;
    line-height: 16px;
    
    наследуется от body

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +    margin-right: 3px;
зачем здесь margin  для .films__year?

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +    padding-top: 1px;
весь padding можно в одну строку записать

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +    font-weight: 500;
font-weight: 500;
 font-size: 12px;
 
 наследуется от body

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_list-cards-movies.scss
> +    line-height: 14px;
line-height: 14px; переписать на относительную величину в 1,16

2021-11-08 10:54 UTC, Viktor-Kostiuchenko commented on src/partial/templates/film-cards.hbs
> +      src="https://upload.wikimedia.org/wikipedia/commons/archive/c/c2/20170210132813%21No_image_poster.png" alt="content photo">
а вот этот src можем переписать вместо ссылки на то, чтобы скачать эту картинку и брать прям оттуда путь

2021-11-08 15:01 UTC, Bohdan-Ta commented on src/partial/templates/film-cards.hbs
> +      src="https://upload.wikimedia.org/wikipedia/commons/archive/c/c2/20170210132813%21No_image_poster.png" alt="content photo">
здесь менять не будем, тут стандартное изоображение. Оно же дефолтное если ничего не подгрузило з базы

2021-11-08 15:05 UTC, Bohdan-Ta commented on src/partial/templates/film-cards.hbs
> +      src="https://upload.wikimedia.org/wikipedia/commons/archive/c/c2/20170210132813%21No_image_poster.png" alt="content photo">
передалал

2021-11-08 15:09 UTC, Bohdan-Ta commented on src/partial/templates/film-cards.hbs
> +      alt="film card" />
исправил

2021-11-08 15:14 UTC, Bohdan-Ta commented on src/partial/templates/film-cards.hbs
> +      <span class="films__info-mark">|</span>
Я бы оставил span, так как не хочу играться. для MVP достаточно, а дальше будем смотреть как оно отрисовывает на сверстаном сайте. Ну если настаиваешь то переделаю

2021-11-08 15:14 UTC, Bohdan-Ta commented on src/partial/templates/film-cards.hbs
> +      <span class="raiting">{{vote_average}}</span>
исправил

2021-11-08 15:15 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +    display: block;
исправил

2021-11-08 15:16 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +    font-weight: 500;
Исправил

2021-11-08 15:17 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +  .films__info-mark,
давай пока оставим span

2021-11-08 15:19 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +    margin-right: 3px;
margin делал для того, что это отдельный елемент и я отодвигаю блок, рейтинг когда он появляется при отрисовке

2021-11-08 15:21 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +    margin-left: 5px;
margin сделал из-за того что это отдельний элемент и я их отодвигаю друг от друга

2021-11-08 15:22 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +  .films__year {
Исправил

2021-11-08 15:26 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +    padding-top: 1px;
исправил

2021-11-08 15:27 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +    line-height: 14px;
исправил

2021-11-08 15:27 UTC, Bohdan-Ta commented on src/sass/layout/_list-cards-movies.scss
> +    font-weight: 500;
исправил

2021-11-08 15:29 UTC, Bohdan-Ta commented on src/partial/layouts/header.html
> +<div class="container main-container">
Переименовал

2021-11-08 15:57 UTC, Viktor-Kostiuchenko approved these changes

2021-11-08 16:04 UTC, Viktor-Kostiuchenko requested changes

2021-11-08 16:04 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/header.html
> +<h1 class="visually-hidden">list movies</h1>
проверить обновление с мейн, чтобы устранить гит конфликт

2021-11-08 16:47 UTC, Viktor-Kostiuchenko approved these changes

2021-11-08 21:33 UTC, merged