Origin/feature/modal
Dron010/filmoteka pull request #26
Opened 2021-11-09 17:24 UTC by Fen111

Add template modal-film.hbs
add styles for modal.scss
add functions for close modal window

2021-11-09 21:07 UTC, Dron010 requested changes

2021-11-09 21:07 UTC, A-V-Kuzmich commented on src/js/components/modal.js
> +backdrop = document.querySelector('.backdrop');
это должно быть в src\js\refs\refs.js

2021-11-09 21:07 UTC, Dron010 commented on src/sass/components/_backdrop.scss
> +    vissibility 250ms cubic-bezier(0.4, 0, 0.2, 1);
взять значения из файла с переменными src\sass\utils\_vars.scss

2021-11-09 21:07 UTC, Dron010 commented on src/sass/components/_modal.scss
> +  cursor: pointer;
cursor: pointer; параметр должен наследоваться с свойства src\sass\base\_reset.scss

2021-11-09 21:07 UTC, Dron010 commented on src/js/components/modal.js
> +
это тут не должно быть, подключить файл и достать нужные

2021-11-09 21:07 UTC, Dron010 commented on src/sass/components/_modal.scss
> +.modal__close-btn {
должно быть наследование базового сброса с src\sass\base\_btn.scss

2021-11-10 07:55 UTC, Dron010 requested changes
допилить

2021-11-10 07:55 UTC, Dron010 commented on src/images/icon/sprite.svg
> +        </symbol>
притир не отработал, поправить форматирование, сделать как все

2021-11-10 07:55 UTC, Dron010 commented on src/js/components/modal.js
> +openModalBtn.addEventListener('click', openModalWindow);
модалка будет открываться не при клике по кнопке а на слушателе ul

2021-11-10 07:55 UTC, Dron010 commented on src/js/components/modal.js
> +backdrop.addEventListener('click', closeToBackdrop);
эти слушатели должны добавляться при открытии модалки и удаляться при закрытии

2021-11-10 07:55 UTC, Dron010 commented on src/partial/templates/modal-film.hbs
> +</div>
Эта штука динамическая, она не загружается вместе со страницей следовательно, и в дереве html его не будет просто меняя класс visually-hidden модалку не нарисуешь. Где то должен быть insertAdjacentHTML который нарисует этот hbs.
Для того что бы понять как эта магия работает жду файла test-modal.js

2021-11-10 09:10 UTC, vladislav-slobodenjuk commented on src/js/components/modal.js
> +openModalBtn.addEventListener('click', openModalWindow);
Слушатель написан у меня, нужен мердж этой ветки чтобы я мог подвязаться. Реф на кнопку и это слушатель надо убрать, а функция открытия остаётся - я ее подхвачу

2021-11-10 15:51 UTC, vladislav-slobodenjuk commented on src/partial/templates/modal-film.hbs
> +</div>
Отрисовывать шаблон тоже я. Будет работать когда добавим ветку

2021-11-10 18:33 UTC, Dron010 approved these changes

2021-11-10 18:34 UTC, merged