Feature/click on logo
Dron010/filmoteka pull request #42
Opened 2021-11-11 15:21 UTC by Falconoff

Исправил ховер на лого (было как-то раздельно и иконка вообще не реагировала). Изменил слушатели на все кнопки хедера (были на контейнерах кнопок, а не на самих кнопках), переделал код под эти изменения. Добавил ф-ции на кнопки Лого, Home и Library. Добавил очистку инпута от введённого запроса при клике на кнопки.

2021-11-11 20:21 UTC, Dron010 requested changes
Думаю что после обновления хедера и нава с ссылками эта ветка будет не нужна. Перед повторной отправкой слить с актуальным мейном

2021-11-12 18:29 UTC, Dron010 requested changes
допилить

2021-11-12 18:29 UTC, A-V-Kuzmich commented on src/js/layout/click-on-logo.js
> +}
Что это делает? при клике на лого в ссылке будет href="././index.html"> и оно будет загружать страницу по дефолту. Зачем этот код? Что он делает?

2021-11-12 18:29 UTC, A-V-Kuzmich commented on src/js/layout/header.js
> +  refs.homeBtn.classList.remove('header__nav-item--active');
это тогл!

2021-11-12 18:29 UTC, A-V-Kuzmich commented on src/js/layout/header.js
> +  refs.homeBtn.classList.add('header__nav-item--active');
ТОГЛ

2021-11-12 18:29 UTC, A-V-Kuzmich commented on src/js/layout/header.js
> +  refs.watchedBtn.classList.add('header__item-btn--active');
ТОГЛ

2021-11-12 18:29 UTC, A-V-Kuzmich commented on src/js/layout/header.js
> +  refs.queueBtn.classList.add('header__item-btn--active');
ТОГЛ

2021-11-12 18:29 UTC, Dron010 commented on src/index.js
> +// import './js/layout/click-on-logo';
удалить

2021-11-12 19:26 UTC, Falconoff commented on src/js/layout/header.js
> +  refs.homeBtn.classList.remove('header__nav-item--active');
это приттиер!

2021-11-12 19:27 UTC, Falconoff commented on src/js/layout/header.js
> +  refs.homeBtn.classList.add('header__nav-item--active');
это приттиер!

2021-11-12 19:27 UTC, Falconoff commented on src/js/layout/header.js
> +  refs.watchedBtn.classList.add('header__item-btn--active');
это приттиер!

2021-11-12 19:27 UTC, Falconoff commented on src/js/layout/header.js
> +  refs.queueBtn.classList.add('header__item-btn--active');
это приттиер!

2021-11-12 19:27 UTC, Falconoff commented on src/index.js
> +// import './js/layout/click-on-logo';
удалил

2021-11-12 19:27 UTC, Falconoff commented on src/js/layout/click-on-logo.js
> +}
удалено

2021-11-14 15:31 UTC, merged