Feature/scroll up
Dron010/filmoteka pull request #43
Opened 2021-11-11 18:43 UTC by T-jorven

2021-11-11 20:15 UTC, Dron010 requested changes
поправить и перед отправкой слить с актуальным мейном

2021-11-11 20:15 UTC, A-V-Kuzmich commented on src/index.html
> +    <include src="./partial/layouts/scroll-top.html"></include>
создай папочку в src\partial\components 
перемести файл scroll-top.html  туда, 
include сделай после footer перед script

2021-11-11 20:15 UTC, A-V-Kuzmich commented on src/js/components/scroll-to-top.js
> +const scrollTarget = document.querySelector(".header");
перенести в src\js\refs\refs.js тут подключить

2021-11-11 20:15 UTC, Dron010 commented on src/sass/components/scroll-top.scss
> +    fill: $accent-hover-color;
добавь прозрачность opacity: 0.5; а при ховере  opacity: 1;

2021-11-11 20:15 UTC, Dron010 commented on src/sass/components/scroll-top.scss
> +  height: 80px;
поставь 
  width: 50px;
  height: 50px;

2021-11-14 23:16 UTC, Viktor-Kostiuchenko requested changes

2021-11-14 23:16 UTC, Viktor-Kostiuchenko commented on src/images/icon/sprite.svg
> +      <path d="M26.667 7.303l-1.97-1.97-7.808 7.808-7.808-7.808-1.97 1.97 7.808 7.808-7.808 7.808 1.97 1.97 7.808-7.808 7.808 7.808 1.97-1.97-7.808-7.808 7.808-7.808z"></path>
Наталия, у тебя сейчас на иконке скрола какой-то таинственный крестик поверх него
заходи в sprite и вот этот path удали, он лишний (начинается с path d="M26.667....)

2021-11-14 23:16 UTC, Viktor-Kostiuchenko commented on src/sass/components/_scroll-top.scss
> +html {
вот это css-правило лучше вынеси туда, где прописаны стили для body (_global-style.scss)

2021-11-14 23:16 UTC, Viktor-Kostiuchenko commented on src/images/icon/sprite.svg
>      <symbol id="icon-heart" viewBox="0 0 34 32">
Общее впечатление - классно! 
Буквально мелкие правки и сливаем
Единственное, я не сильно углублялся - почему ракета на десктопной версии долетев до конца еще раз мигает. Есть идеи?

2021-11-15 17:25 UTC, T-jorven commented on src/sass/components/_scroll-top.scss
> +html {
я поки не буду його виносити, бо можливо я заміню це на джс, бо хром має проблеми з цим правилом

2021-11-15 18:14 UTC, Dron010 requested changes
убрать закомментированный код

2021-11-15 18:14 UTC, Dron010 commented on src/partial/components/scroll-top.html
> +<!--   <div class="rocket-tail"></div>  -->
зачем закомментированный див? Если не нужен - удалить

2021-11-15 18:54 UTC, Dron010 approved these changes

2021-11-15 18:55 UTC, merged