Feature/spiner
Dron010/filmoteka pull request #47
Opened 2021-11-11 22:50 UTC by Bohdan-Ta

2021-11-11 23:30 UTC, Viktor-Kostiuchenko requested changes

2021-11-11 23:30 UTC, Viktor-Kostiuchenko commented on src/index.html
> +    <div id="page-preloader" class="backdrop">
вынеси это в partial и подключи сюда как include

2021-11-11 23:30 UTC, Viktor-Kostiuchenko commented on src/js/api/api-service.js
> +  //showSpiner();// здесь функция работает, спинер запускает.
отправил тебе в личку скрин что здесь нужно сделать

2021-11-11 23:30 UTC, Viktor-Kostiuchenko commented on src/sass/components/_spiner.scss
> +    // opacity: 0;
почистить вот эти комменты

2021-11-12 06:40 UTC, Bohdan-Ta commented on src/sass/components/_spiner.scss
> +    // opacity: 0;
почищено

2021-11-12 06:45 UTC, Bohdan-Ta commented on src/js/api/api-service.js
> +  //showSpiner();// здесь функция работает, спинер запускает.
Поправил

2021-11-12 06:57 UTC, Bohdan-Ta commented on src/index.html
> +    <div id="page-preloader" class="backdrop">
сделал

2021-11-12 08:58 UTC, vladislav-slobodenjuk commented on src/js/api/api-service.js
> +    .then(response => {
Then после catch уже наверно не сработает. Здесь нужен блок .finally()

2021-11-12 11:59 UTC, Viktor-Kostiuchenko commented on src/js/api/api-service.js
> +    .then(response => {
Я с Андреем общался, мы думаю вообще вернём эту функцию в тот вид, что вместе на мозговом штурме сделали.

2021-11-12 13:22 UTC, Viktor-Kostiuchenko requested changes

2021-11-12 13:22 UTC, Viktor-Kostiuchenko commented on src/js/layout/fetch-by-keyword.js
> +            } createInnerMarkup(refs.filmsEl,  filmsTemplate, response.results)
Вот эту строку проверь, там на картинке, что я отправил она отличалась (а именно как передавать аргументы - filmsTemplate(response.results)

2021-11-12 13:22 UTC, Viktor-Kostiuchenko commented on src/js/api/api-service.js
> +.finally(hideSpiner())
Это надо проверить, отработает ли если именно в finaly запихнуть. А то я тебе скидывал скрин где мы этот hideSpiner юзали в then после получения респонс. Смогу чуть позже глянуть

2021-11-12 19:51 UTC, Bohdan-Ta commented on src/js/layout/fetch-by-keyword.js
> +            } createInnerMarkup(refs.filmsEl,  filmsTemplate, response.results)
исправил, но оно не отрабатывает

2021-11-12 20:44 UTC, Bohdan-Ta commented on src/js/api/api-service.js
> +.finally(hideSpiner())
так не работает
даже не запускает спиннер

2021-11-12 21:01 UTC, Dron010 requested changes
поправь...

2021-11-12 21:01 UTC, A-V-Kuzmich commented on src/js/refs/refs.js
> +    pagePreloader: document.getElementById('page-preloader'),//бек-дроп
коменты убери

2021-11-12 21:01 UTC, Dron010 commented on src/js/layout/fetch-by-keyword.js
закомментируй clearFilmsMarkup и ее вызов

2021-11-12 21:06 UTC, Bohdan-Ta commented on src/js/refs/refs.js
> +    pagePreloader: document.getElementById('page-preloader'),//бек-дроп
убрал

2021-11-12 21:08 UTC, Bohdan-Ta commented on src/js/layout/fetch-by-keyword.js
сделано

2021-11-12 21:17 UTC, Dron010 approved these changes

2021-11-12 21:17 UTC, merged