Feature/fixed code for header
Dron010/filmoteka pull request #51
Opened 2021-11-12 23:41 UTC by DashaPash

2021-11-13 13:49 UTC, Dron010 requested changes
слить с мейном перед отправкой. 
Тут на вскидку не более 35 строчек кода в файле. 
два слушателя, две исполняющие функции. 
почистить refs от лишнего. 
Подумать над оптимизацией количества классов. заменив их на модификаторы (--active)

2021-11-13 13:49 UTC, A-V-Kuzmich commented on src/index.js
> +// import './js/layout/click-on-logo';
что это за подключение?

2021-11-13 13:49 UTC, Dron010 commented on src/js/layout/header.js
> +  }
тут можно еще сократить код else if - выкинуть а в первом поставить логический оператор 'watched' || 'queue'
вызывать одну и ту же функцию которая по toggleClass (2 строчки меняла классы кнопкам)

2021-11-13 13:49 UTC, Dron010 commented on src/js/layout/header.js
> +  }
тут можно еще сократить код else if - выкинуть а в первом поставить логический оператор 'library' || 'home'
вызывать одну и ту же функцию которая по toggleClass отрабатывала

2021-11-13 13:49 UTC, Dron010 commented on src/js/layout/header.js
> +}
совместить новые функции в одну...

2021-11-13 13:49 UTC, Dron010 commented on src/js/layout/header.js
> +
это свалка по принципу "Эй, малой, скажи малому...." функции убрать свойства добавить в одну

2021-11-13 13:49 UTC, Dron010 commented on src/js/layout/header.js
>  }
тут две строчки кода 
function watchedBtnActive() {
  refs.queueBtn.classList.toggle('header__item-btn--active');
  refs.watchedBtn.classList.toggle('header__item-btn--active');
}
зачем две функции с этим жестким копипастом?

2021-11-13 13:49 UTC, Dron010 commented on src/js/layout/header.js
> +  watchedBtnActive();
Не вижу смысла в этом переключении... Что бы сохранить последнее положение кнопок нужно выносить из функции в буль, + дописывать это взаимодействие. Убрать этот вызов, он бесполезен. Тем более если переходить между вкладками этот вызов всегда сам будет менять активную кнопку а это баг...

2021-11-13 13:49 UTC, Dron010 commented on src/js/layout/header.js
> +}
Это что за БДСМ? Я такой еще реализации toggle не видел. Тут две строчки:
refs.header.classList.toggle('header__main-bckg')
refs.header.classList.toggle('header__secondary-bckg')
Убрать вызов и эту функцию.

2021-11-13 13:49 UTC, Dron010 commented on src/js/layout/header.js
> +  toggleClass(refs.header, 'header__main-bckg', 'header__secondary-bckg');
убрать этот вызов.. это 2 строчки Toggle

2021-11-14 12:10 UTC, Dron010 requested changes

2021-11-14 12:10 UTC, A-V-Kuzmich commented on src/js/layout/header.js
> +  if (e.srcElement.dataset.action === 'library' || e.srcElement.dataset.action === 'home') {
'library' || 'home' - тоже работает.

2021-11-14 12:10 UTC, A-V-Kuzmich commented on src/js/layout/header.js
> +  if (e.srcElement.dataset.action === 'watched' || e.srcElement.dataset.action === 'queue') {
'watched' || 'queue'- тоже работает

2021-11-14 15:26 UTC, DashaPash commented on src/js/layout/header.js
> +  if (e.srcElement.dataset.action === 'watched' || e.srcElement.dataset.action === 'queue') {
+

2021-11-14 15:26 UTC, DashaPash commented on src/js/layout/header.js
> +  if (e.srcElement.dataset.action === 'library' || e.srcElement.dataset.action === 'home') {
+

2021-11-14 15:31 UTC, Dron010 approved these changes

2021-11-14 15:31 UTC, merged