Origin switch them
Dron010/filmoteka pull request #58
Opened 2021-11-14 20:53 UTC by LarysaTymoshenko

2021-11-14 22:53 UTC, Viktor-Kostiuchenko requested changes

2021-11-14 22:53 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/header.html
> +        <!-- Switch theme -->
комменты можно сразу убирать

2021-11-14 22:53 UTC, Viktor-Kostiuchenko commented on src/partial/layouts/header.html
> +        <!-- End switch theme -->
комменты можна сразу убирать

2021-11-14 22:53 UTC, Viktor-Kostiuchenko commented on src/js/layout/switchTheme.js
Очень даже хорошо! 
1) Еще б я сделал немного более видимым эффект ховера на карточку (при темной теме) 
2) Перекрась крестик в модалке в светлый цвет (при темной теме) 
3) Ну и собственно - смена солнышка на луну (при темной теме)

2021-11-15 15:39 UTC, LarysaTymoshenko commented on src/partial/layouts/header.html
> +        <!-- Switch theme -->
+

2021-11-15 22:00 UTC, Viktor-Kostiuchenko requested changes

2021-11-15 22:00 UTC, Viktor-Kostiuchenko commented on src/images/icon/sprite.svg
>  <svg aria-hidden="true" style="position:absolute;width:0;height:0" xmlns="http://www.w3.org/2000/svg" overflow="hidden">
Со стилями и переключением - все хорошо. Но ты ее поместила в секцию header searcher - а он скрывается при переключении между home и library. И, следовательно, прячет и твою иконку.
Попробуй тогда:
1) задать position relative на header container и уже тогда относительно него выравнивать (не забудь про то, чтобы выровнять для мобилки, планшета и десктопа)
2) перенести свою секцию за секцию header searcher

2021-11-16 17:32 UTC, Dron010 requested changes
поправь

2021-11-16 17:32 UTC, Dron010 commented on src/js/layout/header.js
> +      s;
s; убрать оно тут лишнее

2021-11-16 18:11 UTC, Dron010 approved these changes

2021-11-16 18:11 UTC, merged