Feature/translate
Dron010/filmoteka pull request #64
Opened 2021-11-16 15:10 UTC by Bohdan-Ta

2021-11-17 23:48 UTC, Dron010 requested changes
Поправить, слить с мейном. Повешать перевод в отсутствующих секциях

2021-11-17 23:48 UTC, Dron010 commented on src/js/layout/changeLanguages.js
> +// console.dir(document.querySelector('.header__form-input'))
убрать консоль закомментированную

2021-11-17 23:48 UTC, Dron010 commented on src/js/layout/changeLanguages.js
> +  //     "en": "Add-watched",
если он нужен тогда раскомментировать, если нет убрать

2021-11-17 23:48 UTC, Dron010 commented on src/js/api/api-service.js
> +.get(`${query}&api_key=${API_KEY}&language=${LG}`)
LG - это телефон? Lang еще ладно...

2021-11-18 14:11 UTC, Bohdan-Ta commented on src/js/layout/changeLanguages.js
> +  //     "en": "Add-watched",
пока убрал

2021-11-18 14:12 UTC, Bohdan-Ta commented on src/js/layout/changeLanguages.js
> +// console.dir(document.querySelector('.header__form-input'))
убрал

2021-11-19 12:43 UTC, closed without merging